### ISSUE TITLE
Support TC39 Optional Chaining

### ISSUE THREAD

**Issue by kesslern** [acornjs/acorn-stage3#6]
TC39 added the `.?` operator for null safe object access. Can this be added to Acorn?

**Comment by franktopel** [comment]
We're also eagerly awaiting this since the day we dropped Babel.

**Comment by adrianheine** [comment]
This is still stuck on estree discussions. I'm also probably not going to implement this separately since there's already an acorn PR.

**Comment by guybedford** [comment]
@adrianheine it's unfortunate RollupJS has to be behind other projects here, since eg Babel are involved in those discussions yet are already shipping something. Marjin is traditionally conservative so likely won't push things forward. This means there's a chance all other projects sort of work around this to make something work, leaving RollupJS as the odd one out.

Typically this is exactly the sort of scenario in which being able to use third party plugins allows things to move forward. Especially since Rollup doesn't need to expose the internal parse tree.

Do you think there is anything that can be done on the RollupJS side to help move this forward? There are open collective funds available that could help towards getting something going too if necessary.

**Comment by guybedford** [comment]
(when I describe projects working around the issue I'm talking about what happens if the estree block in the worst case does not get ironed out quickly, and projects do their own things / come to their own consensus, which is increasingly seeming the case)
